// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GalleryImage struct {
	File      string  `json:"file"`
	Thumbnail *string `json:"thumbnail"`
}

type ProofGallery struct {
	ID         string          `json:"id"`
	UploadDate int             `json:"uploadDate"`
	UserAccess []*User         `json:"userAccess"`
	Images     []*GalleryImage `json:"images"`
	Shortlist  []*GalleryImage `json:"shortlist"`
	Favourites []*GalleryImage `json:"favourites"`
}

type User struct {
	Email     string          `json:"email"`
	Name      string          `json:"name"`
	Galleries []*ProofGallery `json:"galleries"`
}
